
all: ParetoBasico 
	g++ -o ParetoBasico ParetoBasico.cpp  
	./ParetoBasico salida1.csv 12345 100
	g++ -o ParetoDyV ParetoSyV.cpp  
	./ParetoDyV salida2.csv 12345 100
clean:
	rm ParetoBasico ParetoDy
	#rm *.txt
	rm *.csv
