
all: ParetoBasico ParetoDyV
	g++ -o ParetoBasico ParetoBasico.cpp  
	./ParetoBasico salida1.csv 

	g++ -o ParetoDyV ParetoDyV.cpp 
	./ParetoDyV salida2.csv 
	
clean:
	rm ParetoBasico ParetoDyV
	#rm *.txt
	rm *.csv
